services:

  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    env_file: .env
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1-1
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

  web:
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/
      - PUBLIC_KEY_URL=http://keycloak:8080/realms/tmp-realm/protocol/openid-connect/certs
    ports:
      - "8000:8000"


volumes:
  local_postgres_data: {}
