services:

  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    env_file: .env
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    ports:
      - '8080:8080'
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev

  web:
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8000:8000"


volumes:
  local_postgres_data: {}
