name: Python application

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  workflow_dispatch:


jobs:
  checks:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Create .env
      run: |
        touch .env
        echo SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7 >> .env
        echo ALGORITHM=HS256 >> .env
        echo ACCESS_TOKEN_EXPIRE_MINUTES=30 >> .env
        echo PUBLIC_KEY_URL=http://localhost:8080/realms/tmp-realm/protocol/openid-connect/certs >> .env


    - name: Set up Poetry
      uses: abatilo/actions-poetry@v4

    - name: Install dependencies
      run: |
        poetry install -vvv

    - name: Check Formatting
      run: make format

    - name: Run Tests
      run: make test
